### ISSUE TITLE
Testing a mirror with --mail argument, does not open email client. 

### ISSUE THREAD

**Issue by pitastrudl** [Torxed/mirrortest#3]
Running ArchLinux with xfce4 and Thunderbird. The command below executes okay but nothing happens afterwards. Tried having Thunderbird open or closed. I am trying to find at what step it's failing. It seems to detect that I do run xfce and it chooses `exo-open` to run but i lost track where exactly it's launching. Is it here?

https://github.com/Torxed/mirrortest/blob/8904edd06412f01c2bdf5a24e7fd8f77e6e05433/mirrortest/mailhandle.py#L231

`python -m mirrortest --tier0 'https://pitastrudl:<token>@repos.archlinux.org/$repo/os/$arch' --mirror 'https://at.arch.mirror.kescher.at/' --mail`

**Comment by Torxed** [comment]
I tested with a dud mirror: `python -m mirrortest --tier0 'https://pitastrudl:<token>@repos.archlinux.org/$repo/os/$arch' --mirror 'http://archlinux.vi-di.fr/' --mail`

As the program won't open a mail without an error, and the kescher.at appears to be working now.

Tested the `--mail` on my laptop, it too did not open the mail.
But in my case it was due to HTTP status codes, and a missing `mailto` for those errors. Added it in PR #5, see if that solved it for you too :)
